Add split_bib to bs4_book
rstudio/bookdown pull request #1185
Opened 2021-06-24 00:35 UTC by shirdekel

- From https://github.com/rstudio/bookdown/issues/1146

2021-06-25 10:22 UTC, cderv requested changes
This seems like a simple change. 

Did you test it against your book ? Did you find any conflict with other features ? 

Can you add a NEWS bullet too ? 

As you added a new argument, you need to document so the CI tests do not error on doc mismatch. thanks !

2021-06-25 10:22 UTC, cderv commented on R/bs4_book.R
> +                     split_bib = split_bib
This should be FALSE by default right ? 
```suggestion
                     split_bib = FALSE
```

Also when adding an argument, it should be added to the documentation here: 
https://github.com/rstudio/bookdown/pull/1185/files#diff-ff358cd3f877c575281978ccf49a2c8869cdcef59cdba125698dc3e8966a570aL41

2021-06-25 23:37 UTC, shirdekel commented
Looks like there's still an issue with the documentation. I tried looking at the `gitbook.R` docs but it's not documented there, only in `html.R`.  Should I give it its own `@param` description as in `html.R`?

2021-07-06 18:01 UTC, cderv commented
Ok I'll have a look at the issue and do it. Thanks !

2021-07-23 09:46 UTC, cderv approved these changes
I have made the change. `split_bib = TRUE` will now be possible to specify in `bs4_book()`. 

This is useful when no CSL with footnote style for citations is used. 
https://pkgs.rstudio.com/bookdown/reference/bs4_book.html#references-bibliography
In that case, `split_bib = TRUE` will do nothing.

When a CSL with footnote style is used, citations are set inline in a linked popup showing on click. This has the same intent a putting the references at the end of the chapter but using a different way to do it.

2021-07-23 09:47 UTC, merged